// マイクロコピーは EM_Tone-Principles に準拠。
// 「治す」「がんばろう」「すごい」などの押し付け系・医療系の語を含めない。

export const copy = {
  app: {
    name: 'Yom-easy',
    tagline: 'あなたに合う読み方を見つけるツール',
    intro: '文字を、あなたに合う見え方に変えてみませんか。',
    placeholder:
      'これから、フォントや色、ふりがな、読み上げなど、自分にぴったり合う読み方を一緒に見つけていきます。',
  },
  modes: {
    edit: '入力',
    read: '読む',
    editAria: 'テキストを入力するモードに切り替える',
    readAria: '入力したテキストを読みやすく表示するモードに切り替える',
  },
  editToggle: {
    open: '✏ 編集する',
    openAria: 'テキストを編集するためのエディタを開く',
    close: '読みに戻る',
    closeAria: 'エディタを閉じて読みに戻る',
  },
  emptyState: {
    title: '読みたい文章を、はじめましょう',
    body: '貼り付ける／ファイルを開く／写真を撮る、好きな方法で文章を入れてください。',
    reassurance: 'サインアップ不要、あなたの端末の中だけで動きます。',
    navigatorPrompt: '初めての方は、こちらから ↓',
    navigatorCta: '💡 読みやすさナビを試す',
    navigatorCtaAria: '読むときの困りごとから合う設定を探すナビを開く',
    paste: '✏ 貼り付ける',
    pasteAria: 'テキストを貼り付けるエディタを開く',
    openFile: '📁 ファイル',
    openFileAria: 'テキストファイル（.txt / .md）を開く',
    camera: '📷 カメラ',
    cameraAria: '写真を撮るか、画像から文字を読み取る',
  },
  drawer: {
    openLabel: '⚙ 設定',
    openAria: '設定パネルを開く',
    closeLabel: '✕',
    closeAria: '設定パネルを閉じる',
  },
  imagePreview: {
    title: '撮った写真',
    imageAlt: '撮影した、または選んだ画像',
    hint: 'この写真から文字を読み取ります。読み取れたら、編集エリアに入ります。間違いがあれば後から直せます。',
    retake: '撮り直す',
    recognize: '文字を読み取る',
    recognizing: '読み取り中…',
    cancel: 'キャンセル',
    cancelAria: '文字の読み取りを中止する',
  },
  ocr: {
    initializing: '読み取りの準備中…',
    loadingModel: '日本語の辞書を読み込み中…',
    preprocessing: '画像を読み取りやすく整えています…',
    recognizing: '文字を読み取り中…',
    cancelled: '読み取りを中止しました。',
    noText: '文字が見つからなかったみたい。明るいところで、もう一度撮ってみよう。',
    failed: '文字をうまく読み取れなかったみたい。明るいところで、もう一度撮ってみよう。',
    statusFallback: '処理中…',
  },
  tts: {
    play: '🔊 読み上げる',
    playAria: 'テキストを読み上げる',
    pause: '⏸ 一時停止',
    pauseAria: '読み上げを一時停止',
    resume: '▶ 再開',
    resumeAria: '読み上げを再開',
    stop: '⏹ 停止',
    stopAria: '読み上げを停止',
    preparing: '準備中…',
    preparingAria: '読み上げの準備中です',
    unsupported: 'お使いのブラウザは、まだ読み上げ機能に対応していないみたい。',
    noJapaneseVoice:
      'お使いの端末には、日本語の音声が見つからないみたい。OSの設定で日本語音声を追加できる場合があります。',
    nothingToRead: '読み上げる文章が、まだありません。',
    preparingError: '読み上げの準備中に少し問題が起きたみたい。もう一度試してみてください。',
    completed: 'お疲れさま。ここまで読み終わりましたね。',
    completedAria: '読み上げが終わりました',
  },
  reader: {
    textareaLabel: '読みたい文章',
    textareaPlaceholder:
      'ここに、読みたい文章を貼り付けるか、書いてください。\nファイルを開いたり、画面にファイルをドラッグして読み込むこともできます。',
    emptyReadView: '読みたい文章が、まだありません。\n「入力」に切り替えて、貼り付けるか、ファイルを開いてみてください。',
    charCount: (n: number) => `${n} 文字`,
  },
  actions: {
    paste: 'テキストを貼り付ける',
    openFile: '📁 ファイルを開く',
    openFileAria: 'テキストファイル（.txt / .md）を開く',
    capture: '📷 カメラで撮影',
    captureAria: '写真を撮るか、画像ファイルを選ぶ',
    read: '読み上げる',
    pause: '一時停止',
    resume: '再開',
    save: '今の設定を保存',
    share: '🔗 設定を共有',
    shareAria: '今の設定の共有用 URL をクリップボードにコピーする',
    print: '🖨 印刷',
    printAria: '今の文章を印刷する',
    clear: '入力欄を空にする',
  },
  hints: {
    quietSave: '設定はこの端末の中だけに保存されます。',
    noLogin: '登録もログインも必要ありません。',
    pickWhatFits: '読みやすい方を選んでみてください。',
    typoOnOcr: '間違いがあれば直してね。',
    dropToOpen: 'ここにファイルを置くと開けます',
    acceptedTypes: '対応形式：.txt / .md（テキストファイル）',
    shareCopied: '共有用の URL をコピーしました。',
    shareFailed: 'コピーできなかったみたい。アドレスバーの URL を直接コピーしてください。',
    shareNotice: '共有されたリンクから読み込まれた設定で開いています。',
  },
  errors: {
    fileUnreadable: 'このファイル、うまく読み込めなかったみたい。別の方法を試してみよう。',
    fileTooLarge: 'ファイルが少し大きすぎるみたい。短めの文章で試してみよう。',
    fileWrongType: 'このファイル形式は、まだ対応していません。.txt か .md のファイルだと開けます。',
    emptyText: '読みたい文章を貼り付けるか、ファイルを開いてください。',
    cameraDenied: 'カメラが使えないみたい。ファイルから選ぶこともできます。',
    ocrEmpty: '文字が見つからなかったみたい。明るいところで、もう一度撮ってみよう。',
    imageUnreadable: 'この画像、うまく読み込めなかったみたい。別の写真で試してみよう。',
    imageWrongType: '画像のかたちが、まだ対応していないみたい。JPEG か PNG だと開けます。',
    imageTooLarge: '画像が少し大きすぎるみたい。もう一度撮るか、別の画像で試してみよう。',
    ocrComingSoon:
      '文字の読み取りは、もう少し準備中です。次の更新で使えるようになります。',
  },
  settings: {
    panelHeading: '読み方の設定',
    navigatorButton: '💡 読みやすさナビ',
    navigatorButtonAria: '読むときの困りごとから合う設定を探す',
    navigatorButtonHint: '困りごとから設定を探せます',
    groupSeeingLabel: 'A. 見やすさを整える',
    groupSeeingHint: '文字そのものの見え方を変えます。',
    groupReadingLabel: 'B. 読むのを助ける',
    groupReadingHint: '読んでいる場所と、文の区切りを見やすくします。',
    groupAudioLabel: 'C. 音と読み取り',
    groupAudioHint: '聞いて読む、写真から文字を取り込む。',
    fontHeading: 'フォント',
    fontHint: 'ボタン自体が、そのフォントで表示されます。試して、合うものを選んでください。',
    groupJp: '日本語向け',
    groupEn: '英語向け',
    groupOption: '専用フォント（オプション）',
    optionDisclaimer:
      'これらのフォントは、合う方と合わない方がいます。研究では「全員に効く」とは言えていません。試してみて、合えば使う、くらいの気持ちで選んでください。',
    webFontPending:
      'OpenDyslexic はオンラインで読み込みます。Dyslexie は商用フォントのため、合えば端末にインストールしたうえで選んでください。',
    spacingHeading: '文字と行の間隔',
    spacingHint: 'スライダーを動かすと、すぐに見え方が変わります。',
    fontSizeLabel: '文字の大きさ',
    letterSpacingLabel: '字の間（文字どうしの間隔）',
    lineHeightLabel: '行の間（行と行の間隔）',
    wordSpacingLabel: '語の間（単語どうしの間隔）',
    maxWidthLabel: '行の幅',
    maxWidthHint:
      '行が短いほうが読みやすい人と、広いほうが読みやすい人がいます。研究では「狭め（30 文字くらい）」で読みやすくなる人が多いと報告されています。試してみて、合うほうを選んでください。',
    colorHeading: '読みたい文章の色',
    colorHint:
      '読みたい文章の部分だけ、背景と文字の色を変えられます。「あ」の見え方が参考になります。設定パネルやボタンの色はそのままです。',
    customColorHeading: '自由に色を選ぶ',
    customColorHint:
      'プリセットだけでは合わないとき、自分で色を作れます。背景と文字、それぞれ選べます。',
    bgColorLabel: '背景色',
    textColorLabel: '文字色',
    resetToPreset: 'プリセットの色に戻す',
    ttsHeading: '読み上げ',
    ttsHint: '速さや声を変えられます。実際に読み上げて、心地よい設定を見つけてみてください。',
    ttsSpeedLabel: '読み上げの速さ',
    ttsVoiceLabel: '声',
    ttsVoiceDefault: 'おまかせ（端末の標準）',
    ttsParagraphSyncLabel: '読み上げ中の段落をハイライト',
    ttsParagraphSyncHint:
      '読み上げ中の段落だけを薄く色で示します。耳と目をそろえて読むと、内容が頭に入りやすくなることが研究で報告されています。',
    highlightHeading: 'ハイライト',
    highlightHint:
      '行の見えやすさを助ける表示です。3つから1つを選んでください。日本語でも英語でも同じように動きます。',
    lineModeOffLabel: 'なし',
    lineModeOffHint: '何もつけません。',
    lineModeZebraLabel: '隔行で色分け（zebra）',
    lineModeZebraHint:
      '1行ごとに薄い色を交互に塗ります（折り返した行も1行ずつ）。「行を飛ばして読んでしまう」のを防ぐ効果が報告されています。',
    lineModeFlatLabel: '全行に色帯',
    lineModeFlatHint:
      'すべての行に色の帯を入れます（折り返した行も含めて、最終行まで1行ずつ）。今どこを読んでいるか、行の存在を見失いにくくなります。',
    highlightColorHeading: 'ハイライトの色',
    highlightColorHint:
      '色は個人差がとても大きいことが研究で分かっています。「正解の色」は決まっていません。合うものを選んでください。',
    focusModeHeading: '読書フォーカス',
    focusModeHint:
      'いま読んでいる段落だけをはっきり、ほかの段落を少し薄く表示します。まわりの文字が気になりやすい方に向いた表示です。',
    focusModeLabel: '段落フォーカスを使う',
    rubyHeading: 'ふりがな',
    rubyHint:
      '漢字に小さなふりがなを付けます。読みづらい漢字も読める助けになります。初めて ON にすると、辞書の準備に少し時間がかかります。',
    rubyEnableLabel: 'ふりがなを付ける',
    rubyPreparing: 'ふりがなの準備中…',
    rubyError: 'ふりがなの準備に少し問題が起きたみたい。もう一度試してください。',
    wakachiHeading: '分かち書き・文節改行',
    wakachiHint:
      '単語の区切りに、目に見えるスペースを入れます。ひらがなが多い文章で効果が大きく、漢字とまじった文章では効果が薄めです。',
    wakachiEnableLabel: '分かち書きにする',
    chunkedHint:
      '句読点や「〜ので」「〜が」などの区切りで、見える改行を入れます。一度に読むかたまりが短くなるので、長い文がうまく頭に入らないときに試してみてください。',
    chunkedEnableLabel: '文節ごとに改行する',
  },
  onboarding: {
    welcome: 'ようこそ。',
    title: 'あなたに合う読み方を見つけましょう',
    subtitle:
      '3問だけ、お試しください。読みやすいと感じた方を選ぶだけです。正解はありません。',
    skip: '今すぐ使う（あとから設定できます）',
    closing: 'あとからいつでも、設定パネルから何度でも変えられます。',
    progress: (current: number, total: number) => `${current} / ${total}`,
    sampleText:
      '文字を、あなたに合う見え方に変えていきましょう。読みやすさのかたちは、人それぞれです。',
    q1: {
      prompt: 'どちらの文字の形が読みやすいですか？',
      aName: 'UD デジタル教科書体',
      bName: '明朝体',
      bNote: 'うろこ（線の端の飾り）があり、読みにくく感じる方が多いと言われています。',
    },
    q2: {
      prompt: 'どちらの背景色が読みやすいですか？',
      aName: 'やわらかいクリーム',
      bName: 'うすい桃色',
    },
    q3: {
      prompt: 'どちらの行の間が読みやすいですか？',
      aName: '普通（行の間 1.5）',
      bName: '広め（行の間 1.8）',
    },
  },
  aidNavigator: {
    modalTitle: 'あなたに合う読み方を、いっしょに探しましょう',
    modalSubtitle:
      '読むときに困っていることを、いくつでも選んでください。\n選んだことに合いそうな設定を、まとめて試せます。合わなければ、設定パネルでいつでも変えられます。',
    cancel: 'やめる',
    cancelAria: '読みやすさナビを閉じる',
    apply: '選んだことに合う設定を試す',
    applyAria: '選択した困りごとに対応する設定をまとめて適用する',
    applyDisabledHint: '選んだものがありません。気になるところを選んでみてください。',
    issues: {
      blur: {
        label: '文字がぼやけて見える・にじむ感じがする',
        hint: 'はっきりとした輪郭のフォントと、ほどよい字間にします。',
      },
      skipLine: {
        label: '行を読み飛ばしてしまう',
        hint: '1行おきに薄く色を塗り、いま読んでいる段落だけをくっきり見せます。',
      },
      kanji: {
        label: '漢字でつっかえる',
        hint: '漢字の上に、自動でふりがなを付けます。',
      },
      longSentence: {
        label: '長い文がうまく頭に入らない',
        hint: '意味の区切りで改行し、注目している段落だけを濃く表示します。',
      },
      glare: {
        label: '画面が白くてまぶしい・チカチカする',
        hint: '背景をやわらかいクリーム色に、文字を少し落ち着いた色に変えます。',
      },
      soundBetter: {
        label: '自分で読むより、聞いた方が分かりやすい',
        hint: '読み上げの準備をして、いま読んでいる段落が分かるようにします。本文を入れた後、🔊 ボタンから始められます。',
      },
      wideLine: {
        label: '行が長すぎて、目が疲れる',
        hint: '文章の幅を狭めて、目の動きを短くします。',
      },
    },
    noticeApplied: '選んだ困りごとに合う設定を試しています。設定パネルでいつでも変えられます。',
  },
  footer: {
    version: 'ベータ版 v0.9.0',
    versionAria: 'バージョン情報',
    privacy: 'プライバシー',
    privacyAria: 'プライバシーポリシーを別タブで開く',
    credits: 'クレジット',
    creditsAria: 'クレジット（フォント・ライブラリの謝辞）を別タブで開く',
    license: 'ライセンス',
    licenseAria: 'ソースコードのライセンス（MIT）を別タブで開く',
    feedback: 'バグ報告・要望',
    feedbackAria: 'GitHub の Issue を別タブで開く',
  },
} as const;

export type Copy = typeof copy;
